### ISSUE TITLE
Fields of Issue are private

### ISSUE THREAD

**Issue by jonasnick** [nbigaouette/gitlab-api-rs#13]
Hi,

I'm able to get and filter Issues with their library but how can I do something with the object when all its fields are private?

Thank you

**Comment by nbigaouette** [comment]
It shouldn't be; if they are private, it's a bug ;)

Fields are public [on master](https://github.com/nbigaouette/gitlab-api-rs/blob/b2aa738a25d574aa51af2ab356bdb5803e18a1a3/src/serde_types.in.rs#L249-L269) but [they are not on v0.4.0](https://github.com/nbigaouette/gitlab-api-rs/blob/v0.4.0/src/serde_types.in.rs#L249-L269) which is the version crates.io.

I wanted to release a v0.5.0 with some breaking changes (this is one of those) but did not have time to finalize the release.

The next two weeks will still be quite busy, I'm not sure I'l have much time working on this until then. Meanwhile you can always point master the master branch:

```toml
gitlab-api = { git = "https://github.com/nbigaouette/gitlab-api-rs" }
```

**Comment by jonasnick** [comment]
Oh, I didn't realize that it's different on master. Also, thanks for showing how to directly use the repo with cargo.

**Comment by nbigaouette** [comment]
Just wanted to let you know that version 0.5 out!

Should now be as simple as:

```toml
gitlab-api = "0.5.2"
```

in your `Cargo.toml`.

Enjoy! ;)

**Comment by jonasnick** [comment]
Awesome! I'll try it out immediately. Thanks :)
