### ISSUE TITLE
Coveralls can't show source anymore

### ISSUE THREAD

**Issue by nbigaouette** [nbigaouette/gitlab-api-rs#9]
Coveralls coverage report can't show the source files anymore.

For example, the coverage report for 1af1e4f92aa56a96d1b6e959966957052fee60bb does not include the `src` prefix. See https://coveralls.io/github/nbigaouette/gitlab-api-rs?branch=master

Clicking on the source on coveralls.io will report that the file couldn't be found.

Previous reports do have the `src` prefix for files and clicking on them do show the proper source. See for example https://coveralls.io/builds/9200321 for commit  d567c1e.

I believe it is due to the change to `kcov` call in `.travis.yml` in 7612ee729c0415c25387b24e02a93e5a0b99bb3c.

**Comment by nbigaouette** [comment]
See difference between coveralls reports in !8:
* [Report](https://github.com/nbigaouette/gitlab-api-rs/pull/8#issuecomment-265919493) for 98f611c: https://coveralls.io/builds/9200321
* [Report](https://github.com/nbigaouette/gitlab-api-rs/pull/8#issuecomment-265923209) for next commit 168c3f8: https://coveralls.io/builds/9200622

**Comment by nbigaouette** [comment]
The problem can't seem to be fixed from `kcov`. This
```
kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern='/.cargo,target' target/kcov target/debug/gitlab_api-*
```
would be enough, and one has to set the _Git repo sub directory_ directly on coveralls.

On coveralls, clicking on the file that is reported missing and making sure one is logged in, this page shows up:

![111d340c-be18-11e6-966d-d70584d7b9d4](https://cloud.githubusercontent.com/assets/112988/21068128/e3623262-be3d-11e6-942c-83f4f26da520.png)

**Comment by nbigaouette** [comment]
See also notes here: https://github.com/lemurheavy/coveralls-public/issues/886

**Comment by sadikovi** [comment]
@nbigaouette Did you manage to solve the issue of source files not showing in coveralls? I checked out the links - they do not show the source files coverage highlight.

Thanks!
